version: 2
jobs:
  build:
    docker:
      - image: python:3-slim
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r ./fetch/requirements.txt -t ./fetch/src
      - run:
          name: Compress *_lambda_upload.zip
          command: |
            apt-get update
            apt-get install -y zip
            cd fetch/src
            chmod 755 ./* -R
            mkdir -p /tmp/workspace
            zip -r /tmp/workspace/fetch *
      - store_artifacts:
          path: /tmp/workspace/fetch.zip
          destination: fetch_lambda_upload.zip
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - fetch.zip
  release:
    docker:
      - image: python:3-slim
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install libraries
          command: |
            ls
            echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
            apt-get update
            apt-get -t stretch-backports install -y git golang
            export GOPATH=$HOME/go
            echo 'export PATH='"$GOPATH"'/bin:$PATH' >> $BASH_ENV
            go get github.com/tcnksm/ghr
      - run:
          name: Release
          command: |
            VERSION=$(git describe)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/workspace/fetch.zip
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              only:
                - master
